### ISSUE TITLE
Comply exhaustive case check

### ISSUE THREAD

**Issue by bcardiff** [luckyframework/teeplate#1]
I left a PR at https://github.com/mosop/teeplate/pull/17. Since this repo is not a fork i don't see how to submit a PR from my own fork of mosop/teeplate

**Comment by paulcsmith** [comment]
I think we formed because teeplate was not accepting updates. Now that it is we can switch back to using it! Thanks @bcardiff

**Comment by paulcsmith** [comment]
Actually looks like they haven’t merged the Pr so I’ll port over your changes!
